"""
DESCRIPTION:
    FkIk match is tool for matching fkik.
    Works properly in any version of Autodesk Maya.
USAGE:
    You may go to this link for have more detail >>
    project.adiendendra.com/snap_fkik
AUTHOR:
    Adien Dendra
CONTACT:
    adien.dendra@gmail.com | hello@adiendendra.com
VERSION:
    1.0 - 20 September 2020 - Initial Release
***************************************************************
Copyright (C) 2020 Adien Dendra - hello@adiendendra.com>
This is commercial license can not be copied and/or
distributed without the express permission of Adien Dendra
***************************************************************
"""
YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn=True
YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv=None
YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAn=filter
YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbnv=zip
YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbnA=abs
import maya.OpenMaya as om
import pymel.core as pm
YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAn=265
YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAP=0.01*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAn
def YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvbA():
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbnA='AD_MatchFkIk'
 pm.window(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbnA,exists=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn)
 if pm.window(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbnA,exists=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn):
  pm.deleteUI(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbnA)
 with pm.window(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbnA,title='AD Fk/Ik Match',width=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAn+10,height=150):
  with pm.columnLayout(rs=5,co=('both',5),adj=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn):
   pm.text(l='Select Leg/Arm Ctrl Setup:')
   pm.button(label='Match To Fk',width=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAn,height=40,backgroundColor=[0.46,0.86,0.46],command=pm.Callback(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvbn))
   pm.button(label='Match To Ik',width=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAn,height=40,backgroundColor=[0.86,0.46,0.46],command=pm.Callback(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvAb))
   with pm.rowLayout(nc=2,cw2=(32*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAP,32*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAP),cl2=('left','center'),columnAttach=[(1,'both',1*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAP),(2,'both',1*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvbAP)],adj=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn):
    pm.text(l='Adien Dendra | 10/2020 | Ver. 1.0')
    pm.text(l='<a href="http://projects.adiendendra.com/">detail to use>> </a>',hl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn)
   pm.separator(h=2,st="single")
 pm.showWindow()
def YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvbn():
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn=pm.ls(sl=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbP=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Fk_Ik_Attr_Name')
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAnb=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Fk_Value_On')
 if pm.objExists(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Fk_Guide_Joint'):
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAnP=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbP)
  if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAnP==YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAnb:
   return YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]
  else:
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPb=[]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbA=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Limb_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Limb_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnAb=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Fk_Guide_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnAP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Limb_Fk_Guide_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnPb=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Limb_Fk_Guide_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnPA=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Fk_Ctrl')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPbA=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Limb_Fk_Ctrl')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPbn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Limb_Fk_Ctrl')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAb=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'FkIk_Arm_Setup_Controller',s=1)
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'FkIk_Leg_Setup_Controller',s=1)
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPnb=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Aim_Axis')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPnA=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Translate_Aim_Joint')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvAn=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Translate_Aim_Joint')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvAP=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Scale_Aim_Joint')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvnA=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Scale_Aim_Joint')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvnP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Fk_Ctrl_Up_Stretch',s=1)
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvPA=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Fk_Ctrl_Mid_Stretch',s=1)
   if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvnP:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPb=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Stretch_Attr')
   if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAb:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvAn(upper_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnAb,middle_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnAP,lower_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnPb,middle_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPbA,lower_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPbn,upper_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnPA,fkik_setup_controller=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn,value_axis_aim_translate_middle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPnA,value_axis_aim_translate_lower=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvAn,value_axis_aim_scale_upper=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvAP,value_axis_aim_scale_middle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvnA,fk_ctrl_up_stretch=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvnP,fk_ctrl_mid_stretch=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvPA,middle_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbA,upper_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPn,lower_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbP,fk_stretch_axis=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPb)
   if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAn:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvPn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Joint')[0]
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAvn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Fk_Guide_Joint')[0]
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAvP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Fk_Ctrl')[0]
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvAn(upper_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnAb,middle_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnAP,lower_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnPb,middle_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPbA,lower_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPbn,upper_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnPA,fkik_setup_controller=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn,value_axis_aim_translate_middle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPnA,value_axis_aim_translate_lower=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvAn,value_axis_aim_scale_upper=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvAP,value_axis_aim_scale_middle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvnA,fk_ctrl_up_stretch=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvnP,fk_ctrl_mid_stretch=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvPA,end_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAvn,end_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAvP,leg=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn,upper_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPn,middle_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbA,lower_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbP,fk_stretch_axis=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPb)
   pm.setAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbP,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAnb)
 else:
  pm.error('Select arm or leg setup controller for matching to Fk!')
def YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvAb():
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn=pm.ls(sl=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbP=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Fk_Ik_Attr_Name')
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAnv=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Ik_Value_On')
 if pm.objExists(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Ik_Guide_Joint'):
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAnP=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbP)
  if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAnP==YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAnv:
   return YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]
  else:
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAPn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbA=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Limb_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvnbP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Limb_Joint')[0]
   if pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Ik_Guide_Joint',s=1):
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAnP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Ik_Guide_Joint')[0]
   else:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAnP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAPv=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Limb_Ik_Guide_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAPn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Limb_Ik_Guide_Joint')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnvA=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Upper_Limb_Ik_Ctrl',s=1)
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnvP=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Pole_Vector_Ik_Ctrl')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnAv=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Limb_Ik_Ctrl')[0]
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPnb=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Aim_Axis')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnAP=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Middle_Translate_Aim_Joint')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnPv=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Lower_Translate_Aim_Joint')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAb=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'FkIk_Arm_Setup_Controller',s=1)
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'FkIk_Leg_Setup_Controller',s=1)
   if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAb:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvnb(upper_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAnP,middle_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAPv,lower_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAPn,polevector_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnvP,lower_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnAv,upper_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnvA,fkik_setup_controller=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn,)
   if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvPAn:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnPA=[]
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPvA=[]
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPvn=[]
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvPn=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Joint')[0]
    if pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Ik_Guide_Joint',s=1):
     YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPAv=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Ik_Guide_Joint')[0]
    else:
     YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPAv=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Joint')[0]
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPAn=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'End_Limb_Ik_Ctrl')
    if pm.attributeQuery('Rotation_Wiggle',n=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0],ex=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn):
     YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnPA=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Rotation_Wiggle')
     YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPvA=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Ik_Toe_Wiggle_Attr_Name')
     YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPvn=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+'Ik_Toe_Wiggle_Ctrl')
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvnb(upper_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAnP,middle_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAPv,lower_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAPn,polevector_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnvP,lower_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnAv,upper_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnvA,fkik_setup_controller=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn,end_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPAn,rotation_wiggle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbnPA,ik_toe_wiggle_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPvn,ik_toe_wiggle_attr_name=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPvA,end_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPAv,leg=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvn,end_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbvPn)
   pm.setAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbn[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfvAbP,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbAnv)
 else:
  pm.error('Select arm or leg setup controller for matching to Ik!')
def YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvAn(upper_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,middle_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,lower_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,middle_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,lower_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,fkik_setup_controller=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,upper_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,value_axis_aim_translate_middle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,value_axis_aim_translate_lower=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,value_axis_aim_scale_upper=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,value_axis_aim_scale_middle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,fk_ctrl_up_stretch=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,fk_ctrl_mid_stretch=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,upper_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,middle_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,lower_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,end_limb_fk_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,end_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,leg=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,fk_stretch_axis=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv):
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv=pm.xform(upper_limb_fk_jnt,ws=1,q=1,ro=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnA=pm.xform(middle_limb_fk_jnt,ws=1,q=1,ro=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn=pm.xform(lower_limb_fk_jnt,ws=1,q=1,ro=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP=pm.xform(upper_limb_fk_jnt,ws=1,q=1,t=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnb=pm.xform(middle_limb_fk_jnt,ws=1,q=1,t=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP=pm.xform(lower_limb_fk_jnt,ws=1,q=1,t=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb=fkik_setup_controller[0]
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn=pm.listAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb)
 if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAn(lambda x:'_DOTAT_' and '_DOFK_' in x or '_DOTVA_' and '_DOFK_' in x,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn):
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvn=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAn(lambda x:'_DOTAT_' in x and '_DOFK_' in x,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn)
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAn(lambda x:'_DOTVA_' in x and '_DOFK_' in x,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn)
  for YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnv,item_value in YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbnv(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvn,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvP):
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnP=pm.getAttr('%s.%s'%(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnv))
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPv=pm.getAttr('%s.%s'%(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb,item_value))
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPn=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnv.replace('_DOTAT_',',').replace('_DOFK_',',').split(',')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnvb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnvP=' '.join(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPn).split()
   pm.setAttr('%s.%s'%(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnP,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnvb),YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPv)
 pm.xform(upper_limb_ctrl,ws=1,ro=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv[2]))
 pm.xform(middle_limb_ctrl,ws=1,ro=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnA[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnA[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnA[2]))
 pm.xform(lower_limb_ctrl,ws=1,ro=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn[2]))
 if pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Translate_Fk_Ctrl_Exists'):
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnPb=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Fk_Attr_Up_Stretch')
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvb=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Fk_Attr_Mid_Stretch')
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvn=pm.getAttr('%s.%s'%(upper_limb_jnt,fk_stretch_axis))
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbv=pm.getAttr('%s.%s'%(middle_limb_jnt,fk_stretch_axis))
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbn=pm.getAttr('%s.%s'%(lower_limb_jnt,fk_stretch_axis))
  if 'scale' in fk_stretch_axis:
   if pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Fk_Value_Up_Stretch')<1.0:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvn-value_axis_aim_scale_upper
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnb=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv/value_axis_aim_scale_upper
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbA=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnb*10.0
    pm.setAttr(fk_ctrl_up_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnPb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbA)
   else:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvn/value_axis_aim_scale_upper
    pm.setAttr(fk_ctrl_up_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnPb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv)
   if pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Fk_Value_Mid_Stretch')<1.0:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbv-value_axis_aim_scale_middle
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAb=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP/value_axis_aim_scale_middle
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAb*10.0
    pm.setAttr(fk_ctrl_mid_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAP)
   else:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbv/value_axis_aim_scale_middle
    pm.setAttr(fk_ctrl_mid_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP)
  else:
   if pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Fk_Value_Up_Stretch')<1.0:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbv-value_axis_aim_translate_middle
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnb=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv/value_axis_aim_translate_middle
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbA=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnb*10.0
    pm.setAttr(fk_ctrl_up_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnPb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbA)
   else:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbv/value_axis_aim_translate_middle
    pm.setAttr(fk_ctrl_up_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnPb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPnv)
   if pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Fk_Value_Mid_Stretch')<1.0:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbn-value_axis_aim_translate_lower
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAb=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP/value_axis_aim_translate_lower
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAb*10.0
    pm.setAttr(fk_ctrl_mid_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvAP)
   else:
    YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPbn/value_axis_aim_translate_lower
    pm.setAttr(fk_ctrl_mid_stretch[0]+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAPvb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvbP)
 else:
  pm.xform(upper_limb_ctrl,ws=1,t=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP[2]))
  pm.xform(middle_limb_ctrl,ws=1,t=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnb[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnb[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnb[2]))
  pm.xform(lower_limb_ctrl,ws=1,t=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP[2]))
 if leg:
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb=pm.xform(end_limb_fk_jnt,ws=1,q=1,ro=1)
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA=pm.xform(end_limb_fk_jnt,ws=1,q=1,t=1)
  pm.xform(end_limb_ctrl,ws=1,ro=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb[2]))
  pm.xform(end_limb_ctrl,ws=1,t=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA[2]))
def YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvnb(upper_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,middle_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,lower_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,polevector_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,lower_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,upper_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,fkik_setup_controller=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,end_limb_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,end_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,rotation_wiggle=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,ik_toe_wiggle_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,ik_toe_wiggle_attr_name=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,end_limb_ik_jnt=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,leg=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv):
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv=pm.xform(upper_limb_ik_jnt,ws=1,q=1,ro=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn=pm.xform(lower_limb_ik_jnt,ws=1,q=1,ro=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP=pm.xform(upper_limb_ik_jnt,ws=1,q=1,t=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnb=pm.xform(middle_limb_ik_jnt,ws=1,q=1,t=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP=pm.xform(lower_limb_ik_jnt,ws=1,q=1,t=1)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb=fkik_setup_controller[0]
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn=pm.listAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb)
 if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAn(lambda x:'_DOTAT_' and '_DOIK_' in x or '_DOTVA_' and '_DOIK_' in x,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn):
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvn=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAn(lambda x:'_DOTAT_' in x and '_DOIK_' in x,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn)
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvP=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAn(lambda x:'_DOTVA_' in x and '_DOIK_' in x,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPn)
  for YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnv,item_value in YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbnv(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvn,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbvP):
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnP=pm.getAttr('%s.%s'%(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnv))
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPv=pm.getAttr('%s.%s'%(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb,item_value))
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPn=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnv.replace('_DOTAT_',',').replace('_DOIK_',',').split(',')
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnvb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnvP=' '.join(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPn).split()
   pm.setAttr('%s.%s'%(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbnP,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAnvb),YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAbPv)
 if pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Upper_Limb_Ik_Ctrl',s=1):
  pm.xform(upper_limb_ctrl,ws=1,ro=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfbPnv[2]))
  pm.xform(upper_limb_ctrl,ws=1,t=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP[2]))
 pm.xform(lower_limb_ctrl,ws=1,ro=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbn[2]))
 pm.xform(lower_limb_ctrl,ws=1,t=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP[2]))
 if leg:
  if not pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'End_Limb_Ik_Ctrl',s=1):
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb=pm.getAttr(end_limb_jnt+'.'+rotation_wiggle)
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbvP=pm.getAttr(fkik_setup_controller[0]+'.'+'Reverse_Wiggle_Value')
   if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbvP:
    pm.setAttr('%s.%s'%(ik_toe_wiggle_ctrl,ik_toe_wiggle_attr_name),(-1*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb))
   else:
    pm.setAttr('%s.%s'%(ik_toe_wiggle_ctrl,ik_toe_wiggle_attr_name),YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb)
  else:
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA=pm.xform(end_limb_ik_jnt,ws=1,q=1,t=1)
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb=pm.xform(end_limb_ik_jnt,ws=1,q=1,ro=1)
   pm.xform((end_limb_ctrl),ws=1,ro=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPb[2]))
   pm.xform((end_limb_ctrl),ws=1,t=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA[0],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA[1],YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnvPA[2]))
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbAv=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvA(root_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvbP,mid_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnb,end_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnP)
 pm.move(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbAv.x,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbAv.y,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbAv.z,polevector_limb_ctrl)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbAP=pm.getAttr('%s.Joint_Distance_Value_Static'%YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbPv=pm.getAttr('%s.Joint_Distance_Value_Dynamic'%YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb)
 if pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Ik_Snap_Checkbox'):
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbPA=pm.listConnections(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Ik_Snap_Ctrl_Name',s=1)[0]
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAvb=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Ik_Snap_Attr_Name')
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAvP=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Ik_Snap_On')
  YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAbv=pm.getAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvPb+'.'+'Ik_Snap_Off')
  if YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbnA(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbPv)>YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbAP:
   YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvnA(polevector_limb_ctrl=polevector_limb_ctrl,xform_middle_limb_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfAvnb,ik_snap_ctrl_name=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbPA,ik_snap_attr_name=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAvb,ik_snap_on=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAvP)
  else:
   pm.setAttr(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnbPA+'.'+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAvb,YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAbv)
def YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPvnA(polevector_limb_ctrl=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,xform_middle_limb_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,ik_snap_ctrl_name=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,ik_snap_attr_name=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,ik_snap_on=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv):
 pm.setAttr('%s.%s'%(ik_snap_ctrl_name,ik_snap_attr_name),ik_snap_on)
 pm.xform(polevector_limb_ctrl,ws=1,t=(xform_middle_limb_pos[0],xform_middle_limb_pos[1],xform_middle_limb_pos[2]))
def YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbvA(root_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,mid_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv,end_pos=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfPbAv):
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPv=om.MVector(root_pos[0],root_pos[1],root_pos[2])
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPb=om.MVector(mid_pos[0],mid_pos[1],mid_pos[2])
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPvb=om.MVector(end_pos[0],end_pos[1],end_pos[2])
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPvA=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPvb-YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPv)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPbv=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPb-YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPv)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPbA=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPvA*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPbv)/(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPvA*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPvA)
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPAv=YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPvA*YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPbA+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPv
 YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPAb=(YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPb-YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPAv).normal()+YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnAPb
 return YuheMqmKjSsOIHtEliwoBVJNFRcrkWLGzgDdpxQaCTyUXfnPAb
# Created by pyminifier (https://github.com/liftoff/pyminifier)
